- name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://hf_token:$HF_TOKEN@huggingface.co/spaces/PeculiarLibrarian/PADI-Validator-v2 main
